### ISSUE TITLE
[Feat] MapView UI 구성

### ISSUE THREAD

**Issue by jwoo820** [APPSCHOOL1-REPO/finalproject-machacha#10]
## 📌  Feature Issue

- NaverMap UI 구성하기

## 📝  To-do

- [x] Map UI 구성하기(NaverMap clone)
- [x] Custom Marker UI 구성
- [x] MapMarker 선택 시 Modal 뷰 연결(Home -> Detail 뷰)
- [ ] Marker데이터 Firebase 연결
- [ ] Image Clustering 적용
- [ ] Marker 선택 시 해당 Marker 기준으로 Map 이동
