### ISSUE TITLE
[Feat] LoginView, AuthViewModel

### ISSUE THREAD

**Issue by Heodoo** [APPSCHOOL1-REPO/finalproject-machacha#15]
## 📌  Feature Issue

-  소셜로그인에 파이어베이스 auth 연동

## 📝  To-do

- [x] 파이어베이스 auth 기본 설정
- [x] 소셜로그인시 email 받아오기
- [x] 싱글톤패턴 -> EnvironmentObject , [참고사이트](https://jaesung0o0.medium.com/swiftui-environmentobject-ea7012311bdf)
- [x] 최초 로그인시 파이어베이스 auth 추가
- [x] 최초 로그인시 닉네임 입력받고 user data 추가
