### ISSUE TITLE
[Feat] 디테일 뷰 앱 아이콘 기능 구현 및 리뷰 뷰 구성

### ISSUE THREAD

**Issue by jeoneeee** [APPSCHOOL1-REPO/finalproject-machacha#21]
## 📌  Feature Issue
- 디테일 뷰 앱 아이콘 기능 구현 및 리뷰 뷰 구성

## 📝  To-do

- [ ] 찜하기, 가봤어요 아이콘 기능 연결
- [x] 리뷰 썸네일 뷰 만들기
- [x] 리뷰 리스트 뷰 만들기
- [x] 리뷰 ViewModel 만들기
