### ISSUE TITLE
[Feat] RegisterView UI

### ISSUE THREAD

**Issue by Heodoo** [APPSCHOOL1-REPO/finalproject-machacha#27]
## 📌  Feature Issue

-  가게정보를 등록할 UI를 구현합니다
- 현재위치기반 맵 -> 마커 -> 등록버튼 -> 상세정보 입력 ->  등록 -> Alert -> 등록완료

## 📝  To-do

- [x] 현재위치를 보여주는 맵
- [x] 맵 카메라 줌/이동
- [x] 맵에 마커 표시
- [x] 마커표시된 주소 정보(위도,경도) 한글 주소로 변환
- [x] 상세정보 입력 뷰
- [x] 등록 Alert 및 나가기 Alert 
- [x] 등록완료시 완료 소리 또는 진동
