### ISSUE TITLE
[Feat] Map DB 연결

### ISSUE THREAD

**Issue by jwoo820** [APPSCHOOL1-REPO/finalproject-machacha#32]
## 📌  Feature Issue

- Map DB 연결 및 기타 기능 개발

## 📝  To-do

- [x] FoodCart VM 연결
- [ ] 마커 에니메이션 수정
- [ ] 화면 빈 공간 터치 시 해당지역 다시 검색하기 기능 추가
- [ ] ~~마커 클러스터링~~
- [ ] 현재 위치 조회
- [x] 카드뷰 디자인 수정(쫀쫀하게)
- [x] 맵 zoom level 수정
- [x] 전체 필터 추가(마차차 메인 아이콘 추가)
- [ ] 필터 기능
- [x] 검색 탭 icon 변경
- [x] 파베 연결
- [x] 마커가 focus 되었을 때 해당 해당 마커 size UP + 카드뷰 focus 색 변경
