### ISSUE TITLE
[Feat] Profile (2/2)

### ISSUE THREAD

**Issue by GeonHyeongKim** [APPSCHOOL1-REPO/finalproject-machacha#36]
## 📌  Feature Issue

- Profile의 기능들

## 📝  To-do

- [x] 프로필탭 UI 수정
- [x] 프로필수정(닉네임, 사진)
- [x] 언어설정(다국어)
- [x] 회원 탈퇴
- [x] 즐겨찾기, 가봤어요, 리뷰관리, 등록한곳 Navigation 관리
- [x] 공지사항
- [x] 보안쪽 정보
- [ ] 로그인/로그아웃
