### ISSUE TITLE
[Feat] Tab Refactor 

### ISSUE THREAD

**Issue by GeonHyeongKim** [APPSCHOOL1-REPO/finalproject-machacha#37]
## 📌  Feature Issue

- Tab Bar 수정

## 📝  To-do

UI 변경
- [ ] Round 선택
- [ ] 기기별 크기 조절
- [ ] 쪼갤수 있는 View 조절
- [ ] 환경변수로 TabManager 조절
