### ISSUE TITLE
[Feat] 관리자 앱

### ISSUE THREAD

**Issue by GeonHyeongKim** [APPSCHOOL1-REPO/finalproject-machacha#41]
## 📌  Feature Issue

관리자(Admin) 앱

## 📝  To-do

- [ ] 사용자가 요청한 포장마차 등록에 대한 승인
- [ ] 신고한 가게 삭제
- [ ] 매거진 작성
- [ ] 전체 공지에 작성
