### ISSUE TITLE
[Feat] 맵 안정화 및 push 서버

### ISSUE THREAD

**Issue by jwoo820** [APPSCHOOL1-REPO/finalproject-machacha#48]
## 📌  Feature Issue

- 맵 안정화
- push 서버

## 📝  To-do

- [x] 현재 위치를 받아오지 못하는 문제 해결
- [x] 마커들이 겹침
- [ ] Tag 필터 기능
- [x] text 기반 검색 기능
- [x] 서비스 지역 표시
- [ ] push 서버 만들기
- [x] Cloud function 알아보기
