### ISSUE TITLE
[Feat] 리뷰 & 디테일 마무리 작업

### ISSUE THREAD

**Issue by jeoneeee** [APPSCHOOL1-REPO/finalproject-machacha#49]
## 📌  Feature Issue

- 리뷰 & 디테일 마무리 작업

## 📝  To-do

- [x] 이미지가 하나도 없을때 에러 처리
- [x]  리뷰 ViewModel → 메소드 생성 및 코드 수정
- [x]  스켈레톤 적용
- [x]  즐겨찾기, 가봤어요, 길찾기 기능 넣기
- [ ]  리뷰 페이지네이션
