### ISSUE TITLE
[Feat] Register 기능 디테일 및 마무리

### ISSUE THREAD

**Issue by Heodoo** [APPSCHOOL1-REPO/finalproject-machacha#51]
## 📌  Feature Issue

- 등록 맵 및 등록 뷰 UI 디테일 및 마무리 작업

## 📝  To-do

- [x] 마커 대신 포장마차 이미지
- [x] 수정 버튼 위치 및 텍스트 변경
- [x] 등록 후 뷰 전환 이슈 해결
- [x] 맵에 이전 등록 마커 불러오기
- [x] 등록 맵뷰 UI 디테일
- [x] 현재위치 기반 맵뷰
- [x] 위치 수정시 이전 맵뷰에 이전 등록위치로 이동
