### ISSUE TITLE
[Feat] Login 회원등록, 자동로그인, 로그아웃/회원탈퇴

### ISSUE THREAD

**Issue by Heodoo** [APPSCHOOL1-REPO/finalproject-machacha#54]
## 📌  Feature Issue

- 회원 등록
- 자동로그인
- 로그아웃/회원탈퇴

## 📝  To-do

- [x] 프로필뷰 로그아웃/회원탈퇴 기능
- [x] 자동로그인
- [x] SplashView 를 통해 자동 로그인 시도, 실패시 로그인 화면
- [x] 첫 로그인시 회원 등록 UI 구현 (개인정보이용 동의, 프로필 사진/이름 , 위치허용, 알림허용)
- [x] 애플로그인 유저데이터 생성 및 LoginState 변경
- [ ] 푸쉬알림
